### ISSUE TITLE
Kernel Panic - macOS Ventura 13.2.1 - crash log included

### ISSUE THREAD

**Issue by LevelAdditional79** [tlefko/Huawei-Matebook-X-Pro-Ventura#42]
Hello, 

both on Monterey (12.6.1) and Ventura (13.2.1) I suffer from 'random' kernel panics. Kernel Panics appear to be random. Don't see a correlation with heavy use; happens during casual use and sometimes a couple of minutes after login.

System info: 
Matebook x pro 2018 Mach-W29C
Intel Core i7-8550U @ 1,8GHz
16GB DDR3 RAM
512GB SSD

It appears to be related to NVMe controller. I added my **crashlog**, **config.plist** and **NVMExpress device tree**. 

Except for the 'random' kernel panics, everything else such as WiFi, Bluetooth, Sound, Touchscreen etc works flawlessly. 
Hoping that someone with more knowledge on this topic can point me to the right direction. 

[NVMExpress device tree.txt](https://github.com/tlefko/Matebook-X-Pro-2018-Ventura/files/11072599/NVMExpress.device.tree.txt)
[config.plist.zip](https://github.com/tlefko/Matebook-X-Pro-2018-Ventura/files/11072525/config.plist.zip)
[Crashlog.txt](https://github.com/tlefko/Matebook-X-Pro-2018-Ventura/files/11072527/Crashlog.txt)

**Comment by tlefko** [comment]
Hey, would you mind specifying which NVME drive is your matebook X pro? is
it LiteON

**Comment by LevelAdditional79** [comment]
> Hey, would you mind specifying which NVME drive is your matebook X pro? is it LiteON
> […](#)

Stock SSD --> KXG50ZNV512G TOSHIBA.

**Comment by tlefko** [comment]
@LevelAdditional79 Disable NVMEFix in the config.plist and try this. apparntly there is a conflict between 3rdpartyNVME and NVMEFix. Also, if it doesn't work try using this version of NVMEFix and re-enabling it.
