### ISSUE TITLE
Touchscreen does not work unless I disable SSDT-DTPD.aml

### ISSUE THREAD

**Issue by wiregen** [tlefko/Huawei-Matebook-X-Pro-Ventura#44]
Hello,

I saw there were touchscreen/multi touch functions advertised in your EFI but it seems like I couldn't get it working with the latest EFI unless I disable the SSDT-DTPD.aml - is this by design?

**Comment by tlefko** [comment]
lol yeah my bad, it’s meant to be disabled by default and if you want to save power you can turn it on. it was meant to be in the instructions :)

**Comment by wiregen** [comment]
Awesome! Thanks just making sure
