### ISSUE TITLE
Black screen on OpenCore

### ISSUE THREAD

**Issue by ldan93** [tlefko/Huawei-Matebook-X-Pro-Ventura#45]
Hi ! 
I'm having a problem with the default EFI on my 2018 model : when booting OpenCore, I only get a black screen. But OpenCore is actually running : I can blindly chose a boot option with the keyboard, and with the debug version the logs seem OK (but I don't know where to look at in the logs). 
The only solution I've found is changing ProvideConsoleGop from true to false in config.plist. Then, the text picker shows up. But this is not really elegant (I get verbose at the beginning of the boot process of macOS). 

I tried several releases, from the very first you published to the latest one, on different USB sticks, it doesn't make a difference. 

Do you have any clue on how to investigate this issue ? 

Unrelated note : I wrote the guide on how to unlock CFG on Profzei repo (https://github.com/profzei/Matebook-X-Pro-2018/wiki/Unlock-0xE2-MSR). Feel free to use/copy whatever you need from it :)

**Comment by tlefko** [comment]
Hey @Idan93, okay so this bug I have seen a few times actually. Just to
clarify -v isn't on in the config right? This bug is still unsolved to be
fully honest it seems to be hit and miss with different OC versions for
some matebook firmwares.

Also, that works is awesome and will be sure to implement it soon!

**Comment by tlefko** [comment]
I have attached your work into the wiki

**Comment by ldan93** [comment]
OK, now I feel embarrassed, of course I kept verbose mode in the boot options... 🤦‍♂️
Anyway, this bug is not a big deal, I will just remember to change ProvideConsoleGop when updating to a newer EFI...
Thanks for your assistance !
